### ISSUE TITLE
close CollapsibleSidebar menu issue?

### ISSUE THREAD

**Issue by DipakSkywave** [DrunkOnBytes/flutter_collapsible_sidebar#10]
@RyuuKenshi how to close the CollapsibleSidebar menu on click on the title?

**Comment by RyuuKenshi** [comment]
Hi @DipakSkywave, as of now you cannot do that as the variable which controls the collapsibility is private.
You can only initialize it as you like using the `isCollapsed` parameter. To collapse or expand the sidebar you have to use the toggle button at the bottom.
