### ISSUE TITLE
Add multi-level menu

### ISSUE THREAD

**Issue by maurobotta** [DrunkOnBytes/flutter_collapsible_sidebar#2]
Hi

Nice work 👍 

Support multi level menu ?  2-3 sub menu ?

**Comment by RyuuKenshi** [comment]
Could you please describe it in details. I could add it in further updates.

**Comment by maurobotta** [comment]
Can i to have 2 levels menu ?

CUSTOMERS >
**ORDERS**  >
**INVOICES** >

>

**CUSTOMERS** >
**ORDERS**  >
     OPEN ORDERS
     CLOSED ORDERS
**INVOICES** >

**Comment by RyuuKenshi** [comment]
Sure, I will add this feature in the next version. Thanks a lot for the suggestion.

**Comment by SalahAdDin** [comment]
@RyuuKenshi Is this project still alive?

**Comment by RyuuKenshi** [comment]
Extremely sorry for not updating this repo. You see @SalahAdDin I am a college student and am in my final year, hence a bit busy with my placements going on. I will surely update it once I have even a bit of time free. 

Don't worry I have not forgotten this project. Also if you like you can contribute to this project by creating PRs. I would love others too if they can help me.

**Comment by SalahAdDin** [comment]
@RyuuKenshi my [humble input](https://github.com/RyuuKenshi/flutter_collapsible_sidebar/pull/13).

**Comment by maliksenpai** [comment]
I will work on it

**Comment by ShawermaBox** [comment]
any updates on this?

**Comment by DrunkOnBytes** [comment]
@ShawermaBox, @maliksenpai is working on it.

**Comment by DrunkOnBytes** [comment]
@Spiderbezno @maurobotta @SalahAdDin Problem fixed with latest release. Can you please check the same once.

**Comment by DrunkOnBytes** [comment]
Thanks a lot @maliksenpai for this incredible feature.
