### ISSUE TITLE
Yellow Lines came on Side menu Text

### ISSUE THREAD

**Issue by Surya-Flutter** [DrunkOnBytes/flutter_collapsible_sidebar#21]
Hi Any one please help me out of this issue. The yellow line come across text . How can I remove it. @RyuuKenshi @TheLonelyNull 

<img width="1440" alt="Screenshot 2022-01-02 at 8 43 54 PM" src="https://user-images.githubusercontent.com/95244821/147880203-b004a85c-0d0c-4fe6-a0b5-6d4461054669.png">

**Comment by TheLonelyNull** [comment]
Hi @Surya-Flutter , this is a common issue in flutter if the text does not have a scaffold widget as its parent somewhere in the widget tree. So simply wrapping your page in a scaffold should take care of the yellow lines
