### ISSUE TITLE
CollapsibleItem icon attribute not accepting Image.asset

### ISSUE THREAD

**Issue by VivekSingh2712** [DrunkOnBytes/flutter_collapsible_sidebar#22]
CollapsibleItem icon attribute is coded to use only Icon data which makes it less flexible when we want to use our custom images here.

**Comment by JmyW** [comment]
+1
That would be great if adopt Icon, not IconData. Or add Image option, thanks.

**Comment by DrunkOnBytes** [comment]
@VivekSingh2712 @JmyW Problem fixed with latest release. Can you please check the same once.
