### ISSUE TITLE
How to make RTL collapsible sidebar?

### ISSUE THREAD

**Issue by majidebraa** [DrunkOnBytes/flutter_collapsible_sidebar#23]
How can I set the location of the collapsible sidebar to the end of the view and make it RTL?

**Comment by DrunkOnBytes** [comment]
Hi @majidebraa, with the latest update, we have added support for RTL. For RTL languages, the sidebar will automatically be placed on the right hand side.
Do check it out once, and if it solves your problem, then please close this issue.
