### ISSUE TITLE
I wanna remove avatar and title how i can do that ?

### ISSUE THREAD

**Issue by abdullahehab** [DrunkOnBytes/flutter_collapsible_sidebar#25]

**Comment by RyuuKenshi** [comment]
I don't think that would be ethically correct. You could fork this project, add your changes and do a pull request. That way this project itself would be updated and everybody who is already using this package can access the new version.

Your name will be shown as a contributor to the project as well on GitHub:

![image](https://user-images.githubusercontent.com/47536135/177614631-10ca431e-ae2b-456b-b543-20961699ff38.png)

**Comment by ShaunAtSense** [comment]
Disable Title and Avatar

File: collapsible_sidebar.dart

Added (Line 40) --> this.showTitle = true,
Added (Line 66) --> final showTitle;
Amended (Line 245) --> widget.showTitle ? _avatar : Container(),

Would be great if you could add something like this in.
Awesome Widget!

**Comment by DrunkOnBytes** [comment]
Hi @ShaunAtSense, it would be great if you could update the code and do a pull request.
Do to my job I have not been able to update the package, but I'll definitely review and merge your code if you do a pull request.

This package is welcome to as much open source contribution as possible.

**Comment by DrunkOnBytes** [comment]
Hi @FreddyStraub, @abdullahehab, the ability to remove avatar and title had been added sometime back but I forgot to notify you here.
You can disable the avatar and title by setting the flag `showTitle: false` when defining the CollapsibleSidebar.

Do check it out and if it solves your problem, please close this issue.
