### ISSUE TITLE
when add value to minWidth

### ISSUE THREAD

**Issue by abdullahehab** [DrunkOnBytes/flutter_collapsible_sidebar#26]
how i can make the list of icons  on the center of width 
and selectedIconBox width dynamic with icon size or only around icon not full width

<img width="1203" alt="Screen Shot 2022-06-27 at 1 09 27 PM" src="https://user-images.githubusercontent.com/30800958/175928370-16ce7b25-5740-4905-9a5e-0e44dd1b0956.png">
h

**Comment by maliksenpai** [comment]
I opened pr for this issue
