### ISSUE TITLE
Impossible to focus the child when collapseOnBodyTap is set to false

### ISSUE THREAD

**Issue by jdayssol** [DrunkOnBytes/flutter_collapsible_sidebar#40]
When I set collapseOnBodyTap to false, I cannot focus the child ( main screen ). I need to collapse first the menu to be able to focus a text field for example.
Possible solution: see my merge request...

**Comment by zenkog** [comment]
I also need this. When can we see a published version? Thanks

**Comment by jdayssol** [comment]
https://github.com/DrunkOnBytes/flutter_collapsible_sidebar/pull/41

**Comment by DrunkOnBytes** [comment]
The fix is already merged, will swiftly publish the changes.

**Comment by DrunkOnBytes** [comment]
The fix has been published in collapsible_sidebar: ^2.0.3+3
