### ISSUE TITLE
SubMenu

### ISSUE THREAD

**Issue by DipakSkywave** [DrunkOnBytes/flutter_collapsible_sidebar#7]
@RyuuKenshi 

Can We Add Submenu in Sidebar? 

Like this :
ORDERS >
OPEN ORDERS
CLOSED ORDERS

**Comment by RyuuKenshi** [comment]
Will add that feature shortly.
You too can help by forking this project, adding the feature and making a PR.
I'll definitely add it if it works.

**Comment by SalahAdDin** [comment]
@RyuuKenshi Isn't it enough adding `ExpansionTIle`?

**Comment by RyuuKenshi** [comment]
I tried that but that resulted in a lot of outside bounds (yellow lines). Need to check and re-implement it.

**Comment by SalahAdDin** [comment]
@RyuuKenshi should it be related to [this](https://github.com/RyuuKenshi/flutter_collapsible_sidebar/issues/11)?

**Comment by RyuuKenshi** [comment]
Yes @SalahAdDin.

**Comment by DrunkOnBytes** [comment]
Closing since same as #2.
